version: "3.8"

services:
  server:
    build:
      context: api
    networks:
      - express-api-network

  ui:
    build:
      context: front
    ports:
      - 8088:80
    networks:
      - express-api-network


networks:
  express-api-network: